<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitff8580598dadffaedc42e446a3ee5a3c
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitff8580598dadffaedc42e446a3ee5a3c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitff8580598dadffaedc42e446a3ee5a3c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitff8580598dadffaedc42e446a3ee5a3c::$classMap;

        }, null, ClassLoader::class);
    }
}
